### PR TITLE
1. fix version check bug 2. change to .zst file extension

### PR DESCRIPTION
**Pull request by ghost**
1. check whether PKGBUILD version number is *in* local pacman version (-Qi), if so, consider that package is all ready  newest.

### CODE REVIEW

**Comment by ghost** [comment]
this is my first time creating pr, so apologize if I'm doing it wrong lol

**Comment by noraj** [comment]
thx, I'll have to test this when I can

**Comment by ghost** [comment]
well, seemingly blackman is not maintained any more, closing this pr now.

**Comment by noraj** [comment]
Could you explain the version check bug you fixed?

**Comment by ghost** [comment]
> Could you explain the version check bug you fixed?

Thanks for your review, noraj.
Think I have that in the comment, when I tested this script, the local installed packages version number often had a 1: prefix, which caused mismatch when using the original ==, eg. 1:1.0 and 1.0. So I changed this to check if local version number contains remote one, which is able to skip this scenario. 
And I haven't been using blakarch for some months, maybe the version naming rules changed, which caused your confusion.

**Comment by noraj** [comment]
Sorry for the delay, I expected notptrix or Synray would have review it.

> Think I have that in the comment, when I tested this script, the local installed packages version number often had a 1: prefix

You must be talking about [epoch](https://wiki.archlinux.org/title/PKGBUILD#epoch).

> So I changed this to check if local version number contains remote one, which is able to skip this scenario.

The script should check for `$epoch:$pkgver-$pkgrel` instead of just `$pkgver`. Doing a "check if A is contained in B" is dangerous because it could match 1.2.0 contained in 10.1.2.0 while it's not the same version at all.

> And I haven't been using blakarch for some months, maybe the version naming rules changed, which caused your confusion.

There is no PKGBUILD version logic change, it's plain standard AL PKGBUILD logic. We could have some custom BA logic for pkgver but that won't infer in this check.

**Comment by ghost** [comment]
> Sorry for the delay, I expected notptrix or Synray would have review it.
> 
> > Think I have that in the comment, when I tested this script, the local installed packages version number often had a 1: prefix
> 
> You must be talking about [epoch](https://wiki.archlinux.org/title/PKGBUILD#epoch).
> 
> > So I changed this to check if local version number contains remote one, which is able to skip this scenario.
> 
> The script should check for `$epoch:$pkgver-$pkgrel` instead of just `$pkgver`. Doing a "check if A is contained in B" is dangerous because it could match 1.2.0 contained in 10.1.2.0 while it's not the same version at all.
> 
> > And I haven't been using blakarch for some months, maybe the version naming rules changed, which caused your confusion.
> 
> There is no PKGBUILD version logic change, it's plain standard AL PKGBUILD logic. We could have some custom BA logic for pkgver but that won't infer in this check.

I see, so this pr is useless then. You can close it. Sadly this didn't work :)

**Comment by noraj** [comment]
I just have pushed the xz to zst change on #22

**Pull request closed without merging**
